version: '3'

services:
  
  nginx:
    image: isystk/nginx
#    container_name: isystk-nginx
    build:
      context: "./nginx"
      dockerfile: "Dockerfile"
    ports:
     - "80:80"
     - "443:443"
    restart: always
    volumes:
     - "./nginx/conf.d:/etc/nginx/conf.d"
     - "./nginx/ssl:/etc/nginx/ssl"
     - "./nginx/logs:/var/log/nginx"
     - "./nginx/public:/usr/share/nginx/html"

  mysql:
    image: isystk/mysql
#    container_name: isystk-mysql
    build:
      context: "./mysql"
      dockerfile: "Dockerfile"
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
     - "3306:3306"
    restart: always
    volumes:
     - ./mysql/conf.d:/etc/mysql/conf.d
     - ./mysql/data:/var/lib/mysql
     - ./mysql/logs:/var/log/mysql

  solr:
    image: isystk/solr
#    container_name: isystk-solr
    build:
      context: "./solr"
      dockerfile: "Dockerfile"
    ports:
     - "8983:8983"
    restart: always
    volumes:
      - ./solr/logs:/var/solr/logs
      - ./solr/data:/var/solr/data
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore


  phpmyadmin:
    image: isystk/phpmyadmin
#    container_name: isystk-phpmyadmin
    build:
      context: "./phpmyadmin"
      dockerfile: "Dockerfile"
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    volumes:
     - "./phpmyadmin/sessions:/sessions"
 
  mailhog:
    image: mailhog/mailhog:latest
#    container_name: isystk-mailhog
    ports:
      - 8025:8025
      - 25:1025

  redis:
    image: redis:latest
#    container_name: isystk-redis
    ports:
      - 6379:6379
